language: c
sudo: false
dist: trusty

cache:
  directories:
  - $HOME/.stack
  - .stack-work/
  - $HOME/.local

addons:
  apt:
    packages:
    - libleveldb-dev

before_install:
- export -a && for f in $(declare -F | awk '{ print $3; }'); do eval declare -f -x $f; done
- export PATH=$HOME/.local/bin:$PATH

- .travis/before_install.sh

install:
- .travis/install.sh

script:
- stack -j 2 --no-terminal build --test --pedantic
- stack -j 2 --no-terminal sdist
