language: c
sudo: false
dist: trusty

services:
- docker

cache:
  directories:
  - $HOME/.stack
  - .stack-work/

before_install:
- export PATH=$HOME/.local/bin:$PATH
- .travis/before_install.sh

install:
- .travis/install.sh

script:
- stack -j 2 --no-terminal build --docker --test --pedantic
- stack -j 2 --no-terminal sdist --docker --test-tarball kontiki-raft-classes kontiki-raft kontiki monad-logger-katip
