language: c
sudo: false
dist: trusty

cache:
  directories:
  - $HOME/.stack
  - .stack-work/
  - $HOME/.local

addons:
  apt:
    packages:
    - libleveldb-dev

before_install:
- .travis/before_install.sh
- export PATH=$HOME/.local/bin:$PATH

install:
- .travis/install.sh

script:
- stack -j 2 --no-terminal build --test --pedantic
- stack -j 2 --no-terminal sdist
